In [2]:
import numpy as np

In [2]:
np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [8]:
np.r_['0,2', [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.r_['1,2,0', [1,2,3], [4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [16]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [17]:
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [20]:
np.array([[2, 0], [0, 5]]) @ np.array([[1, 2], [3, 4]])

array([[ 2,  4],
       [15, 20]])

In [22]:
z = np.arange(81).reshape(3,3,3,3)
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [8]:
a = np.arange(5)
b = a.reshape(1,5)

b.T * b

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [12]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)

xx, yy = np.meshgrid(x, y, sparse=True)

yy

array([[-5.00000000e+00],
       [-4.90000000e+00],
       [-4.80000000e+00],
       [-4.70000000e+00],
       [-4.60000000e+00],
       [-4.50000000e+00],
       [-4.40000000e+00],
       [-4.30000000e+00],
       [-4.20000000e+00],
       [-4.10000000e+00],
       [-4.00000000e+00],
       [-3.90000000e+00],
       [-3.80000000e+00],
       [-3.70000000e+00],
       [-3.60000000e+00],
       [-3.50000000e+00],
       [-3.40000000e+00],
       [-3.30000000e+00],
       [-3.20000000e+00],
       [-3.10000000e+00],
       [-3.00000000e+00],
       [-2.90000000e+00],
       [-2.80000000e+00],
       [-2.70000000e+00],
       [-2.60000000e+00],
       [-2.50000000e+00],
       [-2.40000000e+00],
       [-2.30000000e+00],
       [-2.20000000e+00],
       [-2.10000000e+00],
       [-2.00000000e+00],
       [-1.90000000e+00],
       [-1.80000000e+00],
       [-1.70000000e+00],
       [-1.60000000e+00],
       [-1.50000000e+00],
       [-1.40000000e+00],
       [-1.30000000e+00],
       [-1.2

In [13]:
np.meshgrid(x, y)

[array([[-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        ...,
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
        [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9]]),
 array([[-5. , -5. , -5. , ..., -5. , -5. , -5. ],
        [-4.9, -4.9, -4.9, ..., -4.9, -4.9, -4.9],
        [-4.8, -4.8, -4.8, ..., -4.8, -4.8, -4.8],
        ...,
        [ 4.7,  4.7,  4.7, ...,  4.7,  4.7,  4.7],
        [ 4.8,  4.8,  4.8, ...,  4.8,  4.8,  4.8],
        [ 4.9,  4.9,  4.9, ...,  4.9,  4.9,  4.9]])]