In [1]:
import numpy as np

In [2]:
np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [8]:
np.r_['0,2', [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.r_['1,2,0', [1,2,3], [4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [16]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [17]:
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [20]:
np.array([[2, 0], [0, 5]]) @ np.array([[1, 2], [3, 4]])

array([[ 2,  4],
       [15, 20]])

In [22]:
z = np.arange(81).reshape(3,3,3,3)
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])